### ISSUE TITLE
[FE] 2주차 리뷰 반영

### ISSUE THREAD

**Issue by mina-gwak** [mina-gwak/issue-tracker#28]
## 📃 Description

2주차 PR에서 리뷰받은 내용 반영

## ☑ Todo
- [x] 같은 스코프 내의 중복되는 변수명 수정
- [x] calcTwoTimeDifference 함수 수정
- [x] Icon 컴포넌트 구조 변경
- [x] props 전달 방식 변경
- [x] 모달, 팝오버 컴포넌트 이동
