### ISSUE TITLE
[BE] comment, milestone 변경

### ISSUE THREAD

**Issue by leejohy-0223** [mina-gwak/issue-tracker#74]
## 📃 Description
- comment, milestone error debugging

## ☑ Todo
- [x] comment 수정 issue
- [x] editable -> initial, closed, open으로 세분화해서 제공
- [x] DateTime 정상 반영하기(null x)
- [x] 마일스톤 리스트 조회 이슈
